export const keys = [
  {
    keyCode: 192,
    code: 'Backquote',
    keyEn: '`',
    keyEnShift: '-',
    keyRu: 'ё',
    keyRuShift: 'Ё',
  },
  {
    keyCode: 49,
    code: 'Digit1',
    keyEn: '1',
    keyEnShift: '!',
    keyRu: '1',
    keyRuShift: '!',
  },
  {
    keyCode: 50,
    code: 'Digit2',
    keyEn: '2',
    keyEnShift: '@',
    keyRu: '2',
    keyRuShift: '"',
  },
  {
    keyCode: 51,
    code: 'Digit3',
    keyEn: '3',
    keyEnShift: '#',
    keyRu: '3',
    keyRuShift: '№',
  },
  {
    keyCode: 52,
    code: 'Digit4',
    keyEn: '4',
    keyEnShift: '$',
    keyRu: '4',
    keyRuShift: ';',
  },
  {
    keyCode: 53,
    code: 'Digit5',
    keyEn: '5',
    keyEnShift: '%',
    keyRu: '5',
    keyRuShift: '%',
  },
  {
    keyCode: 54,
    code: 'Digit6',
    keyEn: '6',
    keyEnShift: '^',
    keyRu: '6',
    keyRuShift: ':',
  },
  {
    keyCode: 55,
    code: 'Digit7',
    keyEn: '7',
    keyEnShift: '&',
    keyRu: '7',
    keyRuShift: '?',
  },
  {
    keyCode: 56,
    code: 'Digit8',
    keyEn: '8',
    keyEnShift: '*',
    keyRu: '8',
    keyRuShift: '*',
  },
  {
    keyCode: 57,
    code: 'Digit9',
    keyEn: '9',
    keyEnShift: '(',
    keyRu: '9',
    keyRuShift: '(',
  },
  {
    keyCode: 48,
    code: 'Digit0',
    keyEn: '0',
    keyEnShift: ')',
    keyRu: '0',
    keyRuShift: ')',
  },
  {
    keyCode: 189,
    code: 'Minus',
    keyEn: '-',
    keyEnShift: '_',
    keyRu: '-',
    keyRuShift: '_',
  },
  {
    keyCode: 187,
    code: 'Equal',
    keyEn: '=',
    keyEnShift: '+',
    keyRu: '=',
    keyRuShift: '+',
  },
  {
    keyCode: 8,
    code: 'Backspace',
    keyEn: 'Backspace',
    keyEnShift: 'Backspace',
    keyRu: 'Backspace',
    keyRuShift: 'Backspace',
  },
  {
    keyCode: 9,
    code: 'Tab',
    keyEn: 'Tab',
    keyEnShift: 'Tab',
    keyRu: 'Tab',
    keyRuShift: 'Tab',
  },
  {
    keyCode: 81,
    code: 'KeyQ',
    keyEn: 'q',
    keyEnShift: 'Q',
    keyRu: 'й',
    keyRuShift: 'Й',
  },
  {
    keyCode: 87,
    code: 'KeyW',
    keyEn: 'w',
    keyEnShift: 'W',
    keyRu: 'ц',
    keyRuShift: 'Ц',
  },
  {
    keyCode: 69,
    code: 'KeyE',
    keyEn: 'e',
    keyEnShift: 'E',
    keyRu: 'у',
    keyRuShift: 'У',
  },
  {
    keyCode: 82,
    code: 'KeyR',
    keyEn: 'r',
    keyEnShift: 'R',
    keyRu: 'к',
    keyRuShift: 'K',
  },
  {
    keyCode: 84,
    code: 'KeyT',
    keyEn: 't',
    keyEnShift: 'T',
    keyRu: 'е',
    keyRuShift: 'Е',
  },
  {
    keyCode: 89,
    code: 'KeyY',
    keyEn: 'y',
    keyEnShift: 'Y',
    keyRu: 'н',
    keyRuShift: 'Н',
  },
  {
    keyCode: 85,
    code: 'KeyU',
    keyEn: 'u',
    keyEnShift: 'U',
    keyRu: 'г',
    keyRuShift: 'Г',
  },
  {
    keyCode: 73,
    code: 'KeyI',
    keyEn: 'i',
    keyEnShift: 'I',
    keyRu: 'ш',
    keyRuShift: 'Ш',
  },
  {
    keyCode: 79,
    code: 'KeyO',
    keyEn: 'o',
    keyEnShift: 'O',
    keyRu: 'щ',
    keyRuShift: 'Щ',
  },
  {
    keyCode: 80,
    code: 'KeyP',
    keyEn: 'p',
    keyEnShift: 'P',
    keyRu: 'з',
    keyRuShift: 'З',
  },
  {
    keyCode: 219,
    code: 'BracketLeft',
    keyEn: '[',
    keyEnShift: '{',
    keyRu: 'х',
    keyRuShift: 'Х',
  },
  {
    keyCode: 221,
    code: 'BracketRight',
    keyEn: ']',
    keyEnShift: '}',
    keyRu: 'ъ',
    keyRuShift: 'Ъ',
  },
  {
    keyCode: 220,
    code: 'Backslah',
    keyEn: '\\',
    keyEnShift: '|',
    keyRu: '\\',
    keyRuShift: '/',
  },
  {
    keyCode: 46,
    code: 'Delete',
    keyEn: 'Del',
    keyEnShift: 'Del',
    keyRu: 'Del',
    keyRuShift: 'Del',
  },
  {
    keyCode: 20,
    code: 'CapsLock',
    keyEn: 'CapsLock',
    keyEnShift: 'CapsLock',
    keyRu: 'CapsLock',
    keyRuShift: 'CapsLock',
  },
  {
    keyCode: 65,
    code: 'KeyA',
    keyEn: 'a',
    keyEnShift: 'A',
    keyRu: 'ф',
    keyRuShift: 'Ф',
  },
  {
    keyCode: 83,
    code: 'KeyS',
    keyEn: 's',
    keyEnShift: 'S',
    keyRu: 'ы',
    keyRuShift: 'Ы',
  },
  {
    keyCode: 68,
    code: 'KeyD',
    keyEn: 'd',
    keyEnShift: 'D',
    keyRu: 'в',
    keyRuShift: 'В',
  },
  {
    keyCode: 70,
    code: 'KeyF',
    keyEn: 'f',
    keyEnShift: 'F',
    keyRu: 'а',
    keyRuShift: 'А',
  },
  {
    keyCode: 71,
    code: 'KeyG',
    keyEn: 'g',
    keyEnShift: 'G',
    keyRu: 'п',
    keyRuShift: 'П',
  },
  {
    keyCode: 72,
    code: 'KeyH',
    keyEn: 'h',
    keyEnShift: 'H',
    keyRu: 'р',
    keyRuShift: 'Р',
  },
  {
    keyCode: 74,
    code: 'KeyJ',
    keyEn: 'j',
    keyEnShift: 'J',
    keyRu: 'о',
    keyRuShift: 'О',
  },
  {
    keyCode: 75,
    code: 'KeyK',
    keyEn: 'k',
    keyEnShift: 'K',
    keyRu: 'л',
    keyRuShift: 'Л',
  },
  {
    keyCode: 76,
    code: 'KeyL',
    keyEn: 'l',
    keyEnShift: 'L',
    keyRu: 'д',
    keyRuShift: 'Д',
  },
  {
    keyCode: 186,
    code: 'Semicolon',
    keyEn: ';',
    keyEnShift: ':',
    keyRu: 'ж',
    keyRuShift: 'Ж',
  },
  {
    keyCode: 222,
    code: 'Quote',
    keyEn: '\'',
    keyEnShift: '"',
    keyRu: 'э',
    keyRuShift: 'Э',
  },
  {
    keyCode: 13,
    code: 'Enter',
    keyEn: 'Enter',
    keyEnShift: 'Enter',
    keyRu: 'Enter',
    keyRuShift: 'Enter',
  },
  {
    keyCode: 16,
    code: 'ShiftLeft',
    keyEn: 'Shift',
    keyEnShift: 'Shift',
    keyRu: 'Shift',
    keyRuShift: 'Shift',
  },
  {
    keyCode: 90,
    code: 'KeyZ',
    keyEn: 'z',
    keyEnShift: 'Z',
    keyRu: 'я',
    keyRuShift: 'Я',
  },
  {
    keyCode: 88,
    code: 'KeyX',
    keyEn: 'x',
    keyEnShift: 'X',
    keyRu: 'ч',
    keyRuShift: 'Ч',
  },
  {
    keyCode: 67,
    code: 'KeyС',
    keyEn: 'с',
    keyEnShift: 'C',
    keyRu: 'c',
    keyRuShift: 'С',
  },
  {
    keyCode: 86,
    code: 'KeyV',
    keyEn: 'v',
    keyEnShift: 'V',
    keyRu: 'м',
    keyRuShift: 'М',
  },
  {
    keyCode: 66,
    code: 'KeyB',
    keyEn: 'b',
    keyEnShift: 'B',
    keyRu: 'и',
    keyRuShift: 'И',
  },
  {
    keyCode: 78,
    code: 'KeyN',
    keyEn: 'n',
    keyEnShift: 'N',
    keyRu: 'т',
    keyRuShift: 'Т',
  },
  {
    keyCode: 77,
    code: 'KeyM',
    keyEn: 'm',
    keyEnShift: 'M',
    keyRu: 'ь',
    keyRuShift: 'Ь',
  },
  {
    keyCode: 188,
    code: 'Comma',
    keyEn: ',',
    keyEnShift: '<',
    keyRu: 'б',
    keyRuShift: 'Б',
  },
  {
    keyCode: 190,
    code: 'Period',
    keyEn: '.',
    keyEnShift: '>',
    keyRu: 'ю',
    keyRuShift: 'Ю',
  },
  {
    keyCode: 191,
    code: 'Slash',
    keyEn: '/',
    keyEnShift: '?',
    keyRu: '.',
    keyRuShift: ',',
  },
  {
    keyCode: 38,
    code: 'ArrowUp',
    keyEn: '⇑',
    keyEnShift: '⇑',
    keyRu: '⇑',
    keyRuShift: '⇑',
  },
  {
    keyCode: 16,
    code: 'ShiftRight',
    keyEn: 'Shift',
    keyEnShift: 'Shift',
    keyRu: 'Shift',
    keyRuShift: 'Shift',
  },
  {
    keyCode: 17,
    code: 'ControlLeft',
    keyEn: 'Ctrl',
    keyEnShift: 'Ctrl',
    keyRu: 'Ctrl',
    keyRuShift: 'Ctrl',
  },
  {
    keyCode: 91,
    code: 'Meta',
    keyEn: 'Win',
    keyEnShift: 'Win',
    keyRu: 'Win',
    keyRuShift: 'Win',
  },
  {
    keyCode: 18,
    code: 'AltLeft',
    keyEn: 'Alt',
    keyEnShift: 'Alt',
    keyRu: 'Alt',
    keyRuShift: 'Alt',
  },
  {
    keyCode: 32,
    code: 'Space',
    keyEn: '',
    keyEnShift: '',
    keyRu: '',
    keyRuShift: '',
  },
  {
    keyCode: 18,
    code: 'AltRight',
    keyEn: 'Alt',
    keyEnShift: 'Alt',
    keyRu: 'Alt',
    keyRuShift: 'Alt',
  },
  {
    keyCode: 37,
    code: 'ArrowLeft',
    keyEn: '⇐',
    keyEnShift: '⇐',
    keyRu: '⇐',
    keyRuShift: '⇐',
  },
  {
    keyCode: 40,
    code: 'ArrowDown',
    keyEn: '⇓',
    keyEnShift: '⇓',
    keyRu: '⇓',
    keyRuShift: '⇓',
  },
  {
    keyCode: 39,
    code: 'ArrowRight',
    keyEn: '⇒',
    keyEnShift: '⇒',
    keyRu: '⇒',
    keyRuShift: '⇒',
  },
  {
    keyCode: 17,
    code: 'ControlRight',
    keyEn: 'Ctrl',
    keyEnShift: 'Ctrl',
    keyRu: 'Ctrl',
    keyRuShift: 'Ctrl',
  },
];
