export const keys = [
  {
    code: 'Backquote',
    keyEnDown: '`',
    keyEnUp: '-',
    keyEnCaps: '`',
    keyEnShiftCaps: '`',
    keyRuDown: 'ё',
    keyRuUp: 'Ё',
    keyRuCaps: 'Ё',
    keyRuShiftCaps: 'ё',
  },
  {
    code: 'Digit1',
    keyEnDown: '1',
    keyEnUp: '!',
    keyEnCaps: '1',
    keyEnShiftCaps: '!',
    keyRuDown: '1',
    keyRuUp: '!',
    keyRuCaps: '1',
    keyRuShiftCaps: '!',
  },
  {
    code: 'Digit2',
    keyEnDown: '2',
    keyEnUp: '@',
    keyEnCaps: '2',
    keyEnShiftCaps: '@',
    keyRuDown: '2',
    keyRuUp: '"',
    keyRuCaps: '2',
    keyRuShiftCaps: '"',
  },
  {

    code: 'Digit3',
    keyEnDown: '3',
    keyEnUp: '#',
    keyEnCaps: '3',
    keyEnShiftCaps: '#',
    keyRuDown: '3',
    keyRuUp: '№',
    keyRuCaps: '3',
    keyRuShiftCaps: '№',
  },
  {
    code: 'Digit4',
    keyEnDown: '4',
    keyEnUp: '$',
    keyEnCaps: '4',
    keyEnShiftCaps: '$',
    keyRuDown: '4',
    keyRuUp: ';',
    keyRuCaps: '4',
    keyRuShiftCaps: ';',
  },
  {
    code: 'Digit5',
    keyEnDown: '5',
    keyEnUp: '%',
    keyEnCaps: '5',
    keyEnShiftCaps: '%',
    keyRuDown: '5',
    keyRuUp: '%',
    keyRuCaps: '5',
    keyRuShiftCaps: '%',
  },
  {
    code: 'Digit6',
    keyEnDown: '6',
    keyEnUp: '^',
    keyEnCaps: '6',
    keyEnShiftCaps: '^',
    keyRuDown: '6',
    keyRuUp: ':',
    keyRuCaps: '6',
    keyRuShiftCaps: ':',
  },
  {
    code: 'Digit7',
    keyEnDown: '7',
    keyEnUp: '&',
    keyEnCaps: '7',
    keyEnShiftCaps: '&',
    keyRuDown: '7',
    keyRuUp: '?',
    keyRuCaps: '7',
    keyRuShiftCaps: '?',
  },
  {
    code: 'Digit8',
    keyEnDown: '8',
    keyEnUp: '*',
    keyEnCaps: '8',
    keyEnShiftCaps: '*',
    keyRuDown: '8',
    keyRuUp: '*',
    keyRuCaps: '8',
    keyRuShiftCaps: '*',
  },
  {
    code: 'Digit9',
    keyEnDown: '9',
    keyEnUp: '(',
    keyEnCaps: '9',
    keyEnShiftCaps: '(',
    keyRuDown: '9',
    keyRuUp: '(',
    keyRuCaps: '9',
    keyRuShiftCaps: '(',
  },
  {
    code: 'Digit0',
    keyEnDown: '0',
    keyEnUp: ')',
    keyEnCaps: '0',
    keyEnShiftCaps: ')',
    keyRuDown: '0',
    keyRuUp: ')',
    keyRuCaps: '0',
    keyRuShiftCaps: ')',
  },
  {
    code: 'Minus',
    keyEnDown: '-',
    keyEnUp: '_',
    keyEnCaps: '-',
    keyEnShiftCaps: '_',
    keyRuDown: '-',
    keyRuUp: '_',
    keyRuCaps: '-',
    keyRuShiftCaps: '_',
  },
  {
    code: 'Equal',
    keyEnDown: '=',
    keyEnUp: '+',
    keyEnCaps: '=',
    keyEnShiftCaps: '+',
    keyRuDown: '=',
    keyRuUp: '+',
    keyRuCaps: '=',
    keyRuShiftCaps: '+',
  },
  {
    code: 'Backspace',
    keyEnDown: 'Backspace',
    keyEnUp: 'Backspace',
    keyEnCaps: 'Backspace',
    keyEnShiftCaps: 'Backspace',
    keyRuDown: 'Backspace',
    keyRuUp: 'Backspace',
    keyRuCaps: 'Backspace',
    keyRuShiftCaps: 'Backspace',
  },
  {
    code: 'Tab',
    keyEnDown: 'Tab',
    keyEnUp: 'Tab',
    keyEnCaps: 'Tab',
    keyEnShiftCaps: 'Tab',
    keyRuDown: 'Tab',
    keyRuUp: 'Tab',
    keyRuCaps: 'Tab',
    keyRuShiftCaps: 'Tab',
  },
  {
    code: 'KeyQ',
    keyEnDown: 'q',
    keyEnUp: 'Q',
    keyEnCaps: 'Q',
    keyEnShiftCaps: 'q',
    keyRuDown: 'й',
    keyRuUp: 'Й',
    keyRuCaps: 'Й',
    keyRuShiftCaps: 'й',
  },
  {
    code: 'KeyW',
    keyEnDown: 'w',
    keyEnUp: 'W',
    keyEnCaps: 'W',
    keyEnShiftCaps: 'w',
    keyRuDown: 'ц',
    keyRuUp: 'Ц',
    keyRuCaps: 'Ц',
    keyRuShiftCaps: 'ц',
  },
  {
    code: 'KeyE',
    keyEnDown: 'e',
    keyEnUp: 'E',
    keyEnCaps: 'E',
    keyEnShiftCaps: 'e',
    keyRuDown: 'у',
    keyRuUp: 'У',
    keyRuCaps: 'У',
    keyRuShiftCaps: 'у',
  },
  {
    code: 'KeyR',
    keyEnDown: 'r',
    keyEnUp: 'R',
    keyEnCaps: 'R',
    keyEnShiftCaps: 'r',
    keyRuDown: 'к',
    keyRuUp: 'K',
    keyRuCaps: 'К',
    keyRuShiftCaps: 'к',
  },
  {
    code: 'KeyT',
    keyEnDown: 't',
    keyEnUp: 'T',
    keyEnCaps: 'T',
    keyEnShiftCaps: 't',
    keyRuDown: 'е',
    keyRuUp: 'Е',
    keyRuCaps: 'Е',
    keyRuShiftCaps: 'е',
  },
  {
    code: 'KeyY',
    keyEnDown: 'y',
    keyEnUp: 'Y',
    keyEnCaps: 'Y',
    keyEnShiftCaps: 'y',
    keyRuDown: 'н',
    keyRuUp: 'Н',
    keyRuCaps: 'Н',
    keyRuShiftCaps: 'н',
  },
  {
    code: 'KeyU',
    keyEnDown: 'u',
    keyEnUp: 'U',
    keyEnCaps: 'U',
    keyEnShiftCaps: 'u',
    keyRuDown: 'г',
    keyRuUp: 'Г',
    keyRuCaps: 'Г',
    keyRuShiftCaps: 'г',
  },
  {
    code: 'KeyI',
    keyEnDown: 'i',
    keyEnUp: 'I',
    keyEnCaps: 'I',
    keyEnShiftCaps: 'i',
    keyRuDown: 'ш',
    keyRuUp: 'Ш',
    keyRuCaps: 'Ш',
    keyRuShiftCaps: 'ш',
  },
  {
    code: 'KeyO',
    keyEnDown: 'o',
    keyEnUp: 'O',
    keyEnCaps: 'O',
    keyEnShiftCaps: 'o',
    keyRuDown: 'щ',
    keyRuUp: 'Щ',
    keyRuCaps: 'Щ',
    keyRuShiftCaps: 'щ',
  },
  {
    code: 'KeyP',
    keyEnDown: 'p',
    keyEnUp: 'P',
    keyEnCaps: 'P',
    keyEnShiftCaps: 'p',
    keyRuDown: 'з',
    keyRuUp: 'З',
    keyRuCaps: 'З',
    keyRuShiftCaps: 'з',
  },
  {
    code: 'BracketLeft',
    keyEnDown: '[',
    keyEnUp: '{',
    keyEnCaps: '[',
    keyEnShiftCaps: '{',
    keyRuDown: 'х',
    keyRuUp: 'Х',
    keyRuCaps: 'Х',
    keyRuShiftCaps: 'х',
  },
  {
    code: 'BracketRight',
    keyEnDown: ']',
    keyEnUp: '}',
    keyEnCaps: ']',
    keyEnShiftCaps: '}',
    keyRuDown: 'ъ',
    keyRuUp: 'Ъ',
    keyRuCaps: 'Ъ',
    keyRuShiftCaps: 'ъ',
  },
  {
    code: 'Backslash',
    keyEnDown: '\\',
    keyEnUp: '|',
    keyEnCaps: '\\',
    keyEnShiftCaps: '|',
    keyRuDown: '\\',
    keyRuUp: '/',
    keyRuCaps: '\\',
    keyRuShiftCaps: '/',
  },
  {
    code: 'Delete',
    keyEnDown: 'Del',
    keyEnUp: 'Del',
    keyEnCaps: 'Del',
    keyEnShiftCaps: 'Del',
    keyRuDown: 'Del',
    keyRuUp: 'Del',
    keyRuCaps: 'Del',
    keyRuShiftCaps: 'Del',
  },
  {
    code: 'CapsLock',
    keyEnDown: 'CapsLock',
    keyEnUp: 'CapsLock',
    keyEnCaps: 'CapsLock',
    keyEnShiftCaps: 'CapsLock',
    keyRuDown: 'CapsLock',
    keyRuUp: 'CapsLock',
    keyRuCaps: 'CapsLock',
    keyRuShiftCaps: 'CapsLock',
  },
  {
    code: 'KeyA',
    keyEnDown: 'a',
    keyEnUp: 'A',
    keyEnCaps: 'A',
    keyEnShiftCaps: 'a',
    keyRuDown: 'ф',
    keyRuUp: 'Ф',
    keyRuCaps: 'Ф',
    keyRuShiftCaps: 'ф',
  },
  {
    code: 'KeyS',
    keyEnDown: 's',
    keyEnUp: 'S',
    keyEnCaps: 'S',
    keyEnShiftCaps: 's',
    keyRuDown: 'ы',
    keyRuUp: 'Ы',
    keyRuCaps: 'Ы',
    keyRuShiftCaps: 'ы',
  },
  {
    code: 'KeyD',
    keyEnDown: 'd',
    keyEnUp: 'D',
    keyEnCaps: 'D',
    keyEnShiftCaps: 'd',
    keyRuDown: 'в',
    keyRuUp: 'В',
    keyRuCaps: 'В',
    keyRuShiftCaps: 'в',
  },
  {
    code: 'KeyF',
    keyEnDown: 'f',
    keyEnUp: 'F',
    keyEnCaps: 'F',
    keyEnShiftCaps: 'F',
    keyRuDown: 'а',
    keyRuUp: 'А',
    keyRuCaps: 'А',
    keyRuShiftCaps: 'а',
  },
  {
    code: 'KeyG',
    keyEnDown: 'g',
    keyEnUp: 'G',
    keyEnCaps: 'G',
    keyEnShiftCaps: 'g',
    keyRuDown: 'п',
    keyRuUp: 'П',
    keyRuCaps: 'П',
    keyRuShiftCaps: 'п',
  },
  {
    code: 'KeyH',
    keyEnDown: 'h',
    keyEnUp: 'H',
    keyEnCaps: 'H',
    keyEnShiftCaps: 'h',
    keyRuDown: 'р',
    keyRuUp: 'Р',
    keyRuCaps: 'Р',
    keyRuShiftCaps: 'р',
  },
  {
    code: 'KeyJ',
    keyEnDown: 'j',
    keyEnUp: 'J',
    keyEnCaps: 'J',
    keyEnShiftCaps: 'j',
    keyRuDown: 'о',
    keyRuUp: 'О',
    keyRuCaps: 'О',
    keyRuShiftCaps: 'о',
  },
  {
    code: 'KeyK',
    keyEnDown: 'k',
    keyEnUp: 'K',
    keyEnCaps: 'K',
    keyEnShiftCaps: 'k',
    keyRuDown: 'л',
    keyRuUp: 'Л',
    keyRuCaps: 'Л',
    keyRuShiftCaps: 'л',
  },
  {
    code: 'KeyL',
    keyEnDown: 'l',
    keyEnUp: 'L',
    keyEnCaps: 'L',
    keyEnShiftCaps: 'l',
    keyRuDown: 'д',
    keyRuUp: 'Д',
    keyRuCaps: 'Д',
    keyRuShiftCaps: 'д',
  },
  {
    code: 'Semicolon',
    keyEnDown: ';',
    keyEnUp: ':',
    keyEnCaps: ';',
    keyEnShiftCaps: ':',
    keyRuDown: 'ж',
    keyRuUp: 'Ж',
    keyRuCaps: 'Ж',
    keyRuShiftCaps: 'ж',
  },
  {
    code: 'Quote',
    keyEnDown: '\'',
    keyEnUp: '"',
    keyEnCaps: '\'',
    keyEnShiftCaps: '\'',
    keyRuDown: 'э',
    keyRuUp: 'Э',
    keyRuCaps: 'Э',
    keyRuShiftCaps: 'э',
  },
  {
    code: 'Enter',
    keyEnDown: 'Enter',
    keyEnUp: 'Enter',
    keyEnCaps: 'Enter',
    keyEnShiftCaps: 'Enter',
    keyRuDown: 'Enter',
    keyRuUp: 'Enter',
    keyRuCaps: 'Enter',
    keyRuShiftCaps: 'Enter',
  },
  {
    code: 'ShiftLeft',
    keyEnDown: 'Shift',
    keyEnUp: 'Shift',
    keyEnCaps: 'Shift',
    keyEnShiftCaps: 'Shift',
    keyRuDown: 'Shift',
    keyRuUp: 'Shift',
    keyRuCaps: 'Shift',
    keyRuShiftCaps: 'Shift',
  },
  {
    code: 'KeyZ',
    keyEnDown: 'z',
    keyEnUp: 'Z',
    keyEnCaps: 'Z',
    keyEnShiftCaps: 'z',
    keyRuDown: 'я',
    keyRuUp: 'Я',
    keyRuCaps: 'Я',
    keyRuShiftCaps: 'я',
  },
  {
    code: 'KeyX',
    keyEnDown: 'x',
    keyEnUp: 'X',
    keyEnCaps: 'X',
    keyEnShiftCaps: 'х',
    keyRuDown: 'ч',
    keyRuUp: 'Ч',
    keyRuCaps: 'Ч',
    keyRuShiftCaps: 'ч',
  },
  {
    code: 'KeyC',
    keyEnDown: 'с',
    keyEnUp: 'C',
    keyEnCaps: 'C',
    keyEnShiftCaps: 'c',
    keyRuDown: 'c',
    keyRuUp: 'С',
    keyRuCaps: 'С',
    keyRuShiftCaps: 'с',
  },
  {
    code: 'KeyV',
    keyEnDown: 'v',
    keyEnUp: 'V',
    keyEnCaps: 'V',
    keyEnShiftCaps: 'v',
    keyRuDown: 'м',
    keyRuUp: 'М',
    keyRuCaps: 'М',
    keyRuShiftCaps: 'м',
  },
  {
    code: 'KeyB',
    keyEnDown: 'b',
    keyEnUp: 'B',
    keyEnCaps: 'B',
    keyEnShiftCaps: 'b',
    keyRuDown: 'и',
    keyRuUp: 'И',
    keyRuCaps: 'И',
    keyRuShiftCaps: 'и',
  },
  {
    code: 'KeyN',
    keyEnDown: 'n',
    keyEnUp: 'N',
    keyEnCaps: 'N',
    keyEnShiftCaps: 'n',
    keyRuDown: 'т',
    keyRuUp: 'Т',
    keyRuCaps: 'Т',
    keyRuShiftCaps: 'т',
  },
  {
    code: 'KeyM',
    keyEnDown: 'm',
    keyEnUp: 'M',
    keyEnCaps: 'M',
    keyEnShiftCaps: 'm',
    keyRuDown: 'ь',
    keyRuUp: 'Ь',
    keyRuCaps: 'Ь',
    keyRuShiftCaps: 'ь',
  },
  {
    code: 'Comma',
    keyEnDown: ',',
    keyEnUp: '<',
    keyEnCaps: ',',
    keyEnShiftCaps: '<',
    keyRuDown: 'б',
    keyRuUp: 'Б',
    keyRuCaps: 'Б',
    keyRuShiftCaps: 'б',
  },
  {
    code: 'Period',
    keyEnDown: '.',
    keyEnUp: '>',
    keyEnCaps: '.',
    keyEnShiftCaps: '>',
    keyRuDown: 'ю',
    keyRuUp: 'Ю',
    keyRuCaps: 'Ю',
    keyRuShiftCaps: 'ю',
  },
  {
    code: 'Slash',
    keyEnDown: '/',
    keyEnUp: '?',
    keyEnCaps: '/',
    keyEnShiftCaps: '?',
    keyRuDown: '.',
    keyRuUp: ',',
    keyRuCaps: '.',
    keyRuShiftCaps: ',',
  },
  {
    code: 'ArrowUp',
    keyEnDown: '⇑',
    keyEnUp: '⇑',
    keyEnCaps: '⇑',
    keyEnShiftCaps: '⇑',
    keyRuDown: '⇑',
    keyRuUp: '⇑',
    keyRuCaps: '⇑',
    keyRuShiftCaps: '⇑',
  },
  {
    code: 'ShiftRight',
    keyEnDown: 'Shift',
    keyEnUp: 'Shift',
    keyEnCaps: 'Shift',
    keyEnShiftCaps: 'Shift',
    keyRuDown: 'Shift',
    keyRuUp: 'Shift',
    keyRuCaps: 'Shift',
    keyRuShiftCaps: 'Shift',
  },
  {
    code: 'ControlLeft',
    keyEnDown: 'Ctrl',
    keyEnUp: 'Ctrl',
    keyEnCaps: 'Ctrl',
    keyEnShiftCaps: 'Ctrl',
    keyRuDown: 'Ctrl',
    keyRuUp: 'Ctrl',
    keyRuCaps: 'Ctrl',
    keyRuShiftCaps: 'Ctrl',
  },
  {
    code: 'MetaLeft',
    keyEnDown: 'Win',
    keyEnUp: 'Win',
    keyEnCaps: 'Win',
    keyEnShiftCaps: 'Win',
    keyRuDown: 'Win',
    keyRuUp: 'Win',
    keyRuCaps: 'Win',
    keyRuShiftCaps: 'Win',
  },
  {
    code: 'AltLeft',
    keyEnDown: 'Alt',
    keyEnUp: 'Alt',
    keyEnCaps: 'Alt',
    keyEnShiftCaps: 'Alt',
    keyRuDown: 'Alt',
    keyRuUp: 'Alt',
    keyRuCaps: 'Alt',
    keyRuShiftCaps: 'Alt',
  },
  {
    code: 'Space',
    keyEnDown: '',
    keyEnUp: '',
    keyEnCaps: '',
    keyEnShiftCaps: '',
    keyRuDown: '',
    keyRuUp: '',
    keyRuCaps: '',
    keyRuShiftCaps: '',
  },
  {
    code: 'AltRight',
    keyEnDown: 'Alt',
    keyEnUp: 'Alt',
    keyEnCaps: 'Alt',
    keyEnShiftCaps: 'Alt',
    keyRuDown: 'Alt',
    keyRuUp: 'Alt',
    keyRuCaps: 'Alt',
    keyRuShiftCaps: 'Alt',
  },
  {
    code: 'ArrowLeft',
    keyEnDown: '⇐',
    keyEnUp: '⇐',
    keyEnCaps: '⇐',
    keyEnShiftCaps: '⇐',
    keyRuDown: '⇐',
    keyRuUp: '⇐',
    keyRuCaps: '⇐',
    keyRuShiftCaps: '⇐',
  },
  {
    code: 'ArrowDown',
    keyEnDown: '⇓',
    keyEnUp: '⇓',
    keyEnCaps: '⇓',
    keyEnShiftCaps: '⇓',
    keyRuDown: '⇓',
    keyRuUp: '⇓',
    keyRuCaps: '⇓',
    keyRuShiftCaps: '⇓',
  },
  {
    code: 'ArrowRight',
    keyEnDown: '⇒',
    keyEnUp: '⇒',
    keyEnCaps: '⇒',
    keyEnShiftCaps: '⇒',
    keyRuDown: '⇒',
    keyRuUp: '⇒',
    keyRuCaps: '⇒',
    keyRuShiftCaps: '⇒',
  },
  {
    code: 'ControlRight',
    keyEnDown: 'Ctrl',
    keyEnUp: 'Ctrl',
    keyEnCaps: 'Ctrl',
    keyEnShiftCaps: 'Ctrl',
    keyRuDown: 'Ctrl',
    keyRuUp: 'Ctrl',
    keyRuCaps: 'Ctrl',
    keyRuShiftCaps: 'Ctrl',
  },
];
